/* Project data — sourced from salmanuiux.com/project (shared portfolio with Salman Ansari) */
window.PROJECTS = [
  {
    slug: 'schoolpad',
    num: '01',
    title: 'Schoolpad',
    sub: 'Modern, intuitive B2B2C school platform',
    desc: 'Transforming a legacy school management system into a modern, intuitive B2B2C platform serving admins, teachers, staff, students, and parents.',
    services: 'EdTech · School ERP',
    tags: ['EdTech', 'School ERP', 'B2B2C'],
    quote: 'They didn\u2019t just design for our brand\u2014they designed with our voice. The result is more than visual\u2014it\u2019s an experience that speaks like us.',
    quoteBy: 'Team Schoolpad',
    img: 'https://framerusercontent.com/images/Bj3Bpt3LvUXhaauJ5zd8vrXkYS0.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/schoolpad',
  },
  {
    slug: 'design-school',
    num: '02',
    title: 'Chitkara Design School',
    sub: 'Creative, youthful, professional identity',
    desc: 'Crafting a creative, youthful, yet professional digital identity for a modern design school \u2014 blending narrative with thoughtful information architecture.',
    services: 'Design \u00b7 UX Strategy \u00b7 Branding \u00b7 Website',
    tags: ['EdTech', 'Branding', 'Website'],
    quote: 'We needed bold. What we got was fearless. He helped us distill energy into a design that moves with purpose.',
    quoteBy: 'Saurabh Sharma',
    img: 'https://framerusercontent.com/images/uHaFvS6s8e9nlIqoY2oLzKeYF2M.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/design-school',
  },
  {
    slug: 'fintap',
    num: '03',
    title: 'FinTap',
    sub: 'Finance at your fingertips',
    desc: 'A mobile fintech app for the UAE market enabling users to manage balances, invest, and transact confidently through a clean, trust-focused interface.',
    services: 'Product/UX \u00b7 Strategy \u00b7 Mobile App',
    tags: ['Fintech', 'Mobile', 'UAE'],
    quote: 'Designing for fintech requires trust, and you understood that instinctively. Every interaction felt deliberate and confidence-building.',
    quoteBy: 'Team FinTap',
    img: 'https://framerusercontent.com/images/VNoovAnh8QQ1qC6AGu2SZxWCrk.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/fintap',
  },
  {
    slug: 'lifey',
    num: '04',
    title: 'Lifey',
    sub: 'Water at your doorstep',
    desc: 'A subscription-based water delivery app for UAE users that simplifies recurring orders, fast delivery scheduling, and access to trusted water brands.',
    services: 'Visual Identity \u00b7 UX Strategy \u00b7 Mobile \u00b7 e-commerce',
    tags: ['Consumer', 'Mobile', 'e-commerce'],
    quote: 'They didn\u2019t just ship an App\u2014they unlocked a new level of clarity in how we present ourselves. Everything just clicks now.',
    quoteBy: 'Taif Tec',
    img: 'https://framerusercontent.com/images/3nxNjjSA8MnKb88lBMVCBAR6NQ.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/lifey---water-at-your-doorstep',
  },
  {
    slug: 'telos',
    num: '05',
    title: 'Telos',
    sub: 'Purposeful wellbeing',
    desc: 'A reflection-led wellbeing platform that helps users consciously improve different areas of life through curated content and thoughtful discussions.',
    services: 'Design \u00b7 UX \u00b7 UI \u00b7 Strategy \u00b7 Website',
    tags: ['Wellbeing', 'Web', 'Platform'],
    quote: 'You brought discipline and clarity to a product that could have easily become noisy or over-engineered. The platform feels intentional and true to vision.',
    quoteBy: 'Raheel Malik',
    img: 'https://framerusercontent.com/images/jyYEZI7xx507EmewKv8mWXzSAjI.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/telos',
  },
  {
    slug: 'atom',
    num: '06',
    title: 'ATOM',
    sub: 'Admissions & lead portal',
    desc: 'Admissions and lead management portal for Chitkara University \u2014 bringing structure to complex enrolment workflows used daily across teams.',
    services: 'Visual Identity \u00b7 UX Strategy \u00b7 Webflow CMS',
    tags: ['EdTech', 'Portal', 'CMS'],
    quote: 'Brought structure to a system that had grown chaotic over time. The portal didn\u2019t just look better\u2014it genuinely improved how our teams worked day to day.',
    quoteBy: 'Saurabh Sharma',
    img: 'https://framerusercontent.com/images/THKS6aiMLRmzWRryRGaTcusW7tQ.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/atom',
  },
  {
    slug: 'e-pay',
    num: '07',
    title: 'E-Pay',
    sub: 'Payments & recharge, UAE',
    desc: 'A mobile payment and recharge app designed for the UAE market \u2014 reliable, fast, and stress-free across recurring everyday transactions.',
    services: 'Mobile App \u00b7 UX \u00b7 UI',
    tags: ['Fintech', 'Mobile', 'UAE'],
    quote: 'He consistently delivered reliable, user-focused designs across different platforms. Working with him was smooth, clear, and stress-free.',
    quoteBy: 'Taif Tec',
    img: 'https://framerusercontent.com/images/8w9wCP0QiqRcFJyeVHKz65HfCDM.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/e-pay',
  },
  {
    slug: 'simplysales',
    num: '08',
    title: 'Simply Sales / Fluent',
    sub: 'Manufacturing-first CRM',
    desc: 'A manufacturing-first CRM unifying leads, quotations, payments, and customer context into a single system tailored for enterprise workflows.',
    services: 'Web-based CRM \u00b7 B2B \u00b7 Enterprise',
    tags: ['CRM', 'B2B', 'Enterprise'],
    quote: 'Did a great job simplifying a complex sales workflow. The design helped our team work faster and with more clarity.',
    quoteBy: 'Shankar Ramchandran',
    img: 'https://framerusercontent.com/images/HwHeRoYjyNcZw1VLCMIOk1o4gHE.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/simplysales',
  },
  {
    slug: 'jd-world',
    num: '09',
    title: 'JD World',
    sub: 'Bite-sized media, UAE',
    desc: 'A content-first entertainment app for short, fun, bite-sized media designed for the UAE market with a clear, fast browsing flow.',
    services: 'Mobile App \u00b7 UX \u00b7 UI',
    tags: ['Consumer', 'Mobile', 'Media'],
    quote: 'Reliable, user-focused designs across different platforms. Smooth, clear, and stress-free collaboration.',
    quoteBy: 'Taif Tec',
    img: 'https://framerusercontent.com/images/zTAU4ngDBh6zXW18umZeduYx58.png?width=2400&height=1199',
    href: 'https://salmanuiux.com/project/jd-world',
  },
  {
    slug: 'zingit-patient-application',
    num: '10',
    title: 'Zingit Patient App',
    sub: 'Calm, considered healthcare',
    desc: 'A patient-facing mobile app that simplifies booking, rescheduling, and managing healthcare appointments with clarity and control.',
    services: 'Mobile Application \u00b7 UX \u00b7 UI',
    tags: ['Healthcare', 'Mobile'],
    quote: 'The app feels calm, reassuring, and respectful of patient anxiety. You design with empathy, not just efficiency.',
    quoteBy: 'Zingit Team',
    img: 'https://framerusercontent.com/images/GauWMqIcGEYalS1HsMJRBDH8Ts.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/zingit-patient-application',
  },
  {
    slug: 'chitkara-business-school',
    num: '11',
    title: 'Chitkara Business School',
    sub: 'A distinct digital identity',
    desc: 'Building a distinct, modern, professional digital identity for Chitkara\u2019s Business School without breaking the university\u2019s brand foundation.',
    services: 'Strategy \u00b7 UX \u00b7 UI \u00b7 Systems \u00b7 Website',
    tags: ['EdTech', 'Website', 'Brand'],
    quote: 'He gave our business school a distinct, professional digital identity without breaking the university\u2019s brand foundation.',
    quoteBy: 'Saurabh Sharma',
    img: 'https://framerusercontent.com/images/hrPxqjMe5ckdAUAYLf54YcHB70E.png?width=2000&height=1859',
    href: 'https://salmanuiux.com/project/chitkara-business-school',
  },
  {
    slug: 'eld-application',
    num: '12',
    title: 'Electronic Logging Device',
    sub: 'Calm UX for US truckers',
    desc: 'An ELD mobile application for US truckers designed to track driving hours, vehicle status, and regulatory compliance with minimal cognitive load.',
    services: 'Design \u00b7 UX \u00b7 UI \u00b7 Mobile Application',
    tags: ['Compliance', 'Mobile', 'B2B'],
    quote: 'You designed for real people doing demanding work \u2014 low light, long hours, zero patience for complexity. The UX clarity reduced errors and training time.',
    quoteBy: 'Team ELD',
    img: 'https://framerusercontent.com/images/s3UAY3xfxjcD8UIdoOhjwHxBOEs.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/eld-application',
  },
  {
    slug: 'inbox--zingit',
    num: '13',
    title: 'Inbox \u2014 Zingit',
    sub: 'Web messaging & automation',
    desc: 'A responsive web-based messaging and automation platform that brings order to a noisy operational space \u2014 intuitive even for non-technical users.',
    services: 'Design \u00b7 Responsive \u00b7 UX \u00b7 UI',
    tags: ['SaaS', 'Web', 'Messaging'],
    quote: 'The inbox feels intuitive even for non-technical users, which was critical for adoption. You consistently thought about scale and edge cases.',
    quoteBy: 'Zingit Operations',
    img: 'https://framerusercontent.com/images/0W3BthYTER8FVgfY9932A4vCa8.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/inbox--zingit',
  },
  {
    slug: 'chitkara-university',
    num: '14',
    title: 'Chitkara University',
    sub: 'Unified, scalable website',
    desc: 'A unified, scalable, user-centered website built to improve student conversions across the university\u2019s digital footprint.',
    services: 'Product/UX \u00b7 Strategy \u00b7 UI \u00b7 Systems \u00b7 Website',
    tags: ['EdTech', 'Website', 'System'],
    quote: 'Innovative solutions with a strong user-first mindset across our EdTech products. Balanced aesthetics with practical usability.',
    quoteBy: 'Saurabh Sharma',
    img: 'https://framerusercontent.com/images/VacYdLHqYbb6KvuBt5GTwN2WhsE.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/chitkara-university',
  },
  {
    slug: 'icertify',
    num: '15',
    title: 'ICertify',
    sub: 'Certificate creation & verification',
    desc: 'A scalable digital certificate creation, distribution, and verification platform built with intentional detail across the full lifecycle.',
    services: 'Design \u00b7 UX \u00b7 UI \u00b7 Strategy \u00b7 Development',
    tags: ['SaaS', 'Platform', 'Verification'],
    quote: 'Every detail felt intentional. From the first scroll, we knew we were in good hands\u2014our users feel it too.',
    quoteBy: 'Shivani Garg',
    img: 'https://framerusercontent.com/images/WXHXMOEljYNe097mYuK4SxMwOg.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/icertify',
  },
  {
    slug: 'thrilldubai',
    num: '16',
    title: 'ThrillDubai',
    sub: 'Tour booking, reimagined',
    desc: 'A tour booking mobile app that allows users to explore, compare, and reserve curated Dubai experiences with confidence and ease.',
    services: 'Mobile Application \u00b7 UX \u00b7 UI',
    tags: ['Travel', 'Mobile', 'UAE'],
    quote: 'You combined inspiration with clarity \u2014 helping users move faster without hesitation. Design choices directly supported conversion.',
    quoteBy: 'ThrillDubai Team',
    img: 'https://framerusercontent.com/images/l4pvqvuydxvRsZCYFYp06GDUu8.jpg?width=1440&height=843',
    href: 'https://salmanuiux.com/project/thrilldubai',
  },
  {
    slug: 'agency-maison',
    num: '17',
    title: 'Agency Maison',
    sub: 'Premium service, effortless UX',
    desc: 'Where premium service coordination meets effortless digital experience \u2014 a clean, dev-ready system across portal and mobile app.',
    services: 'Design \u00b7 UX \u00b7 UI \u00b7 Web Portal \u00b7 Mobile App',
    tags: ['Service', 'Portal', 'Mobile'],
    quote: 'Helped us design a mobile app for our clients \u2014 understood requirements quickly and delivered clean, development-ready designs.',
    quoteBy: 'Nashid B.',
    img: 'https://framerusercontent.com/images/UsdbIROsQ4qgCzDbQh84KoKc80.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/agency-maison',
  },
  {
    slug: 'my-online-college',
    num: '18',
    title: 'My Online College',
    sub: 'Trust-led discovery',
    desc: 'Optimizing trust and conversions in online education discovery \u2014 structured, confident, and built for clear decision-making at scale.',
    services: 'Design \u00b7 Strategy \u00b7 Development',
    tags: ['EdTech', 'Web', 'Conversion'],
    quote: 'Transformed a crowded, trust-deficit market into a clear and conversion-focused product. The platform feels structured and scalable.',
    quoteBy: 'Team MOC',
    img: 'https://framerusercontent.com/images/2ciLkQd9CQlWfB0u3ERCID5H5BA.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/my-online-college',
  },
  {
    slug: 'campus-360',
    num: '19',
    title: 'Campus 360',
    sub: 'Explore. Experience. Decide.',
    desc: 'A platform that turns a complex university discovery problem into a clear, structured experience students can navigate with confidence.',
    services: 'Design \u00b7 UX \u00b7 UI \u00b7 Web \u00b7 Education',
    tags: ['EdTech', 'Web', 'Discovery'],
    quote: 'Turned a complex discovery problem into a clear, structured platform. Scalable, thoughtful, and purpose-built for long-term journeys.',
    quoteBy: 'Albert',
    img: 'https://framerusercontent.com/images/c9dIoZKGTb0Dhx2ufsHu6GjTl3Q.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/campus-360',
  },
  {
    slug: 'home-decor',
    num: '20',
    title: 'Homely',
    sub: 'Calm, credible interiors brand',
    desc: 'Designing interiors that feel personal, timeless, and intentional \u2014 turning a highly personal service into a calm, credible digital brand.',
    services: 'Brand \u00b7 UX \u00b7 UI \u00b7 Website',
    tags: ['Interiors', 'Brand', 'Website'],
    quote: 'Turned a highly personal design service into a calm, credible digital brand experience.',
    quoteBy: 'Bulander Garg',
    img: 'https://framerusercontent.com/images/kpTUplP8Uh4IGpCIP579z7ttg8.png?width=2400&height=1200',
    href: 'https://salmanuiux.com/project/home-decor',
  },
  {
    slug: 'ui-snapshots',
    num: '21',
    title: 'UI Snapshots',
    sub: 'Interfaces shaped by context',
    desc: 'A curated set of interfaces shaped by context, users, and systems \u2014 spanning research, IA, interaction, mobile UI, and high-fidelity prototyping.',
    services: 'UX Research \u00b7 IA \u00b7 Interaction \u00b7 Mobile UI \u00b7 Prototyping',
    tags: ['Snapshots', 'Systems'],
    quote: '',
    quoteBy: '',
    img: 'https://framerusercontent.com/images/RGdrUSu6pVH5BeW0kKDQnyfkW8.png?width=2000&height=1000',
    href: 'https://salmanuiux.com/project/ui-snapshots',
  },
];
